### ISSUE TITLE
Swap order of PR and Release Tag

### ISSUE THREAD

**Issue by herebefrogs** [js13kGames/bot#8]
The release guide indicates to create the PR before the Release Tag, which causes the bot to fail for lack of bundle.

Instead, the Release Tag should be created before the PR, so the bundle is available when the bot triggers. This is the order mentioned in https://medium.com/js13kgames/brand-new-validation-bot-ce2b4409ac27 (see Process section)

**Comment by Platane** [comment]
The order should not matter. One thing to notice is that on opening a PR, the bot is notified with a hook, but because of api limitation, it is not notified on new release. Instead we have a cron job looking for new release every 10min or so.

So it may looks like it's not working on new release, but it just takes up to 10 min.

( it was previously 2min, so barely noticeable, but that resulted in the bot wasting api calls, which are limited and hitting the limit pretty fast when a ot of PR where to check )

I rather keep the recommended worflow this way. Because the other way leads people to think they need to open a new PR on new release.

**Comment by herebefrogs** [comment]
I understand the technical limitations, but with the current order, the PR
triggers the bot immediately, the bot fails the checks because there is no
release, and since adding a release doesn't trigger the build, people think
they have to push a new commit to retrigger the bot (that what I was
instructed to do rather than wait up to 10min).

At least Release before PR gets the developer an immediate bundle check,
and patience is only required if the bundle needs to be updated. With PR
before Release patience is required immediately to even get the 1st bundle
check.

Submission is a stressing time, given that the majority of game entries are
submitted on the last day/hour, and patience comes in short supply.

An alternative would be to set the expectations in the How To Submit guide
and explain how long one should wait after updating a bundle, just like you
did here, before seeing the new results.

I also understand this might be moot by the time the next compo occurs,
depending how much more work gets done on the bot & submit form.

That being said, I've appreciated the convenience the bot provided.

Cheers,
Jérôme
